/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaJugador;

//import modelo.Fachada;
import controladores.IngresarMesaController;
import java.util.ArrayList;
import modelo.Mesa;
import modelo.UsuarioJugador;
import vistas.vistaIngresarMesa;

/**
 *
 * @author Usuario
 */
public class IngresarMesa extends javax.swing.JDialog implements vistaIngresarMesa {
    
    public UsuarioJugador usuario;
    private IngresarMesaController controlador;
    
    public IngresarMesa(java.awt.Frame parent, boolean modal,UsuarioJugador a) {
        super(parent, modal);
        initComponents();
        setTitle("El Poker - Jugador: " + a.getNombreCompleto().toUpperCase());
        usuario = a;
        controlador = new IngresarMesaController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMesas = new javax.swing.JList<>();
        lblNroMesa = new javax.swing.JLabel();
        lblJugadores = new javax.swing.JLabel();
        lblLuz = new javax.swing.JLabel();
        lblComision = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setText("Jugador:");

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 204, 0));
        lblSaldo.setText("Saldo:");

        listaMesas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMesasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaMesas);

        lblNroMesa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNroMesa.setText("Número de Mesa:");

        lblJugadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJugadores.setText("Jugadores:");

        lblLuz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLuz.setText("Apuesta Base:");

        lblComision.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComision.setText("Porc. de Comisión:");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("INGRESAR");

        lblError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNroMesa, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(lblComision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblNroMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLuz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblComision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaMesasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMesasValueChanged
        seleccionMesa();
    }//GEN-LAST:event_listaMesasValueChanged

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComision;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JLabel lblLuz;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNroMesa;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JList<String> listaMesas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMesas(ArrayList<Mesa> mesas) {
        ArrayList<String> listado = new ArrayList();
        for (Mesa m : mesas) {
            listado.add("Mesa N°" + m.getNumeroMesa());
        }
        //listaMesas.setListData(listado.toArray());
    }

    @Override
    public void mostrarJugador(UsuarioJugador jugador) {
        lblNombre.setText("Jugador:" + jugador.getNombreCompleto());
        lblSaldo.setText("Saldo:" + jugador.getSaldo());
    }
    
    private void seleccionMesa() {
        controlador.seleccionMesa(listaMesas.getSelectedIndex());
    }
    
    @Override
    public void mostrarDetallesMesa(int numeroMesa, int cantidadJugadores, int luz, int comision) {
        lblNroMesa.setText("Número de Mesa: " + numeroMesa);
        lblJugadores.setText("Jugadores: " + cantidadJugadores + " / 5");
        lblLuz.setText("Apuesta base: " + luz);
        lblComision.setText("Porc. Comisión: " + comision);
    }

    @Override
    public void limpiarDetallesJugador() {
        lblNombre.setText("Jugador:");
        lblSaldo.setText("Saldo:");
    }

    @Override
    public void limpiarDetallesMesa() {
        lblNroMesa.setText("Número de Mesa:");
        lblJugadores.setText("Jugadores:");
        lblLuz.setText("Apuesta base:");
        lblComision.setText("Porc. Comisión:");
    }
}
